name: house keeping tools
version: 1.3
tasks:
  - target_dir: /opt/test1
    max_age_in_days:
      days: 1
    max_number_of_files:
      counts: 2
  - target_dir: /opt/test2
    max_age_in_days:
      days: 1
    max_number_of_files:
      counts: 2
  - target_dir: /opt/test3
    max_age_in_days:
      days: 1
    max_number_of_files:
      counts: 2